from object_definitions import (
    VPC_Node, 
    IOL_Node, 
    RHEL_Linux_Node, 
    Network, 
    Windows_Node, 
    Windows_Server_Node, 
    NodeToNetworkConnection, 
    NodeToNodeConnection, 
    Image, 
    Icon, 
    NetworkType,
    DeviceRole
)

hq_network_inventory = [
    Network(name="Management1", type=NetworkType.PNET9, left=150, top=1935),
    Network(name="Management2", type=NetworkType.PNET9, left=1675, top=1935),
    Network(name="Internet", type=NetworkType.PNET0, left=400, top=1750),
]

hq_device_inventory = [
    VPC_Node(name="PC1", left=350, top=2500),
    VPC_Node(name="PC2", left=450, top=2500),
    VPC_Node(name="PC3", left=550, top=2500),
    VPC_Node(name="PC4", left=650, top=2500),
    VPC_Node(name="PC5", left=785, top=2500),
    VPC_Node(name="PC6", left=855, top=2500),
    VPC_Node(name="PC7", left=925, top=2500),
    VPC_Node(name="PC8", left=1000, top=2500),
    VPC_Node(name="PC9", left=1065, top=2500),
    VPC_Node(name="PC10", left=1135, top=2500),
    VPC_Node(name="PC11", left=1205, top=2500),
    VPC_Node(name="PC12", left=1275, top=2500),
    VPC_Node(name="PC13", left=1450, top=2500),
    VPC_Node(name="PC14", left=1562, top=2500),
    VPC_Node(name="PC15", left=1674, top=2500),
    VPC_Node(name="PC16", left=1800, top=2500),
    RHEL_Linux_Node(name="DHCP-Server", image=Image.LINUX_RHEL_10, left=500, top=1775),
    RHEL_Linux_Node(name="Controller",ram=2048 ,image=Image.LINUX_RHEL_8,left=150, top=1750, mgmt_ip="192.168.110.253", prefix_length=24),
    IOL_Node(name="Core-Router", image=Image.IOL_ROUTER, icon=Icon.ROUTER, device_role=DeviceRole.ROUTER, left=1515, top=1125, ethernet=2, mgmt_ip="192.168.110.1"),
    IOL_Node(name="HQ-Edge-Router", image=Image.IOL_ROUTER, icon=Icon.ROUTER, device_role=DeviceRole.ROUTER, left=950, top=1325, ethernet=2, mgmt_ip="192.168.110.2"),
    IOL_Node(name="HQ-Router1", image=Image.IOL_ROUTER, icon=Icon.ROUTER, device_role=DeviceRole.ROUTER ,left=800, top=1550, ethernet=2, mgmt_ip="192.168.110.3"),
    IOL_Node(name="HQ-Router2", image=Image.IOL_ROUTER, icon=Icon.ROUTER, device_role=DeviceRole.ROUTER, left=1100, top=1550, ethernet=2, mgmt_ip="192.168.110.4"),
    IOL_Node(name="HQ-CSW1", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=800, top=1775, ethernet=5, mgmt_ip="192.168.110.5"),
    IOL_Node(name="HQ-CSW2", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=1100, top=1775, ethernet=5, mgmt_ip="192.168.110.6"),
    IOL_Node(name="HQ-DSW1", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=400, top=2000, ethernet=5, mgmt_ip="192.168.110.7"),
    IOL_Node(name="HQ-DSW2", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=600, top=2000, ethernet=5, mgmt_ip="192.168.110.8"),
    IOL_Node(name="HQ-DSW3", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=800, top=2000, ethernet=5, mgmt_ip="192.168.110.9"),
    IOL_Node(name="HQ-DSW4", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=1000, top=2000, ethernet=5, mgmt_ip="192.168.110.10"),
    IOL_Node(name="HQ-DSW5", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=1200, top=2000, ethernet=5, mgmt_ip="192.168.110.11"),
    IOL_Node(name="HQ-DSW6", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L3, left=1400, top=2000, ethernet=5, mgmt_ip="192.168.110.12"),
    IOL_Node(name="HQ-ASW1", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=415, top=2250, ethernet=5, mgmt_ip="192.168.110.13"),
    IOL_Node(name="HQ-ASW2", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=600, top=2250, ethernet=5, mgmt_ip="192.168.110.14"),
    IOL_Node(name="HQ-ASW3", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=850, top=2250, ethernet=5, mgmt_ip="192.168.110.15"),
    IOL_Node(name="HQ-ASW4", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=950, top=2250, ethernet=5, mgmt_ip="192.168.110.16"),
    IOL_Node(name="HQ-ASW5", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=1050, top=2250, ethernet=5, mgmt_ip="192.168.110.17"),
    IOL_Node(name="HQ-ASW6", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=1150, top=2250, ethernet=5, mgmt_ip="192.168.110.18"),
    IOL_Node(name="HQ-ASW7", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=1350, top=2250, ethernet=5, mgmt_ip="192.168.110.19"),
    IOL_Node(name="HQ-ASW8", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=1550, top=2250, ethernet=5, mgmt_ip="192.168.110.20"),
    IOL_Node(name="HQ-ASW9", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, left=1750, top=2250, ethernet=5, mgmt_ip="192.168.110.21"),
]


hq_management_connection_inventory = [
    NodeToNetworkConnection(node="Controller", interface_label="e1", network="Management1"),
    NodeToNetworkConnection(node="Controller", interface_label="e0", network="Internet"),
    NodeToNetworkConnection(node="DHCP-Server", interface_label="e0", network="Management1"),
    NodeToNetworkConnection(node="HQ-Router1", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-CSW1", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-DSW1", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-DSW2", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-DSW3", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-ASW1", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-ASW2", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-ASW3", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-ASW4", interface_label="e0/0", network="Management1"),
    NodeToNetworkConnection(node="HQ-Router2", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-CSW2", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-DSW4", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-DSW5", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-DSW6", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-ASW5", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-ASW6", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-ASW7", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-ASW8", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-ASW9", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="HQ-Edge-Router", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="Core-Router", interface_label="e0/0", network="Management2"),
]

hq_device_connection_inventory = [
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e4/3", node_b="DHCP-Server", interface_b="e1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e0/1", node_b="HQ-CSW2", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e0/2", node_b="HQ-CSW2", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e0/3", node_b="HQ-CSW2", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e1/0", node_b="HQ-CSW2", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e1/1", node_b="HQ-DSW1", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e1/2", node_b="HQ-DSW1", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e1/3", node_b="HQ-DSW2", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e2/0", node_b="HQ-DSW2", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e2/1", node_b="HQ-DSW3", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e2/2", node_b="HQ-DSW3", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e2/3", node_b="HQ-DSW4", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e3/0", node_b="HQ-DSW4", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e3/1", node_b="HQ-DSW5", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e3/2", node_b="HQ-DSW5", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e3/3", node_b="HQ-DSW6", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e4/0", node_b="HQ-DSW6", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e1/1", node_b="HQ-DSW1", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e1/2", node_b="HQ-DSW1", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e1/3", node_b="HQ-DSW2", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e2/0", node_b="HQ-DSW2", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e2/1", node_b="HQ-DSW3", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e2/2", node_b="HQ-DSW3", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e2/3", node_b="HQ-DSW4", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e3/0", node_b="HQ-DSW4", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e3/1", node_b="HQ-DSW5", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e3/2", node_b="HQ-DSW5", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e3/3", node_b="HQ-DSW6", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e4/0", node_b="HQ-DSW6", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e4/1", node_b="HQ-Router1", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW1", interface_a="e4/2", node_b="HQ-Router2", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e4/1", node_b="HQ-Router1", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-CSW2", interface_a="e4/2", node_b="HQ-Router2", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-Router1", interface_a="e0/3", node_b="HQ-Router2", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-Router1", interface_a="e1/0", node_b="HQ-Edge-Router", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-Router2", interface_a="e1/0", node_b="HQ-Edge-Router", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-Edge-Router", interface_a="e0/3", node_b="Core-Router", interface_b="e0/1"),
    NodeToNodeConnection(node_a="Core-Router", interface_a="e0/2", node_b="DataCenter-Router", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW1", interface_a="e1/1", node_b="HQ-DSW2", interface_b="e1/1"),
    NodeToNodeConnection(node_a="HQ-DSW1", interface_a="e1/2", node_b="HQ-DSW2", interface_b="e1/2"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e1/1", node_b="HQ-DSW4", interface_b="e1/1"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e1/2", node_b="HQ-DSW4", interface_b="e1/2"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e1/1", node_b="HQ-DSW6", interface_b="e1/1"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e1/2", node_b="HQ-DSW6", interface_b="e1/2"),
    NodeToNodeConnection(node_a="HQ-DSW1", interface_a="e1/3", node_b="HQ-ASW1", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW1", interface_a="e2/0", node_b="HQ-ASW1", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW1", interface_a="e2/1", node_b="HQ-ASW2", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW1", interface_a="e2/2", node_b="HQ-ASW2", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW2", interface_a="e1/3", node_b="HQ-ASW1", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW2", interface_a="e2/0", node_b="HQ-ASW1", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW2", interface_a="e2/1", node_b="HQ-ASW2", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW2", interface_a="e2/2", node_b="HQ-ASW2", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e1/3", node_b="HQ-ASW3", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e2/0", node_b="HQ-ASW3", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e2/1", node_b="HQ-ASW4", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e2/2", node_b="HQ-ASW4", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e2/3", node_b="HQ-ASW5", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e3/0", node_b="HQ-ASW5", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e3/1", node_b="HQ-ASW6", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW3", interface_a="e3/2", node_b="HQ-ASW6", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e1/3", node_b="HQ-ASW3", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e2/0", node_b="HQ-ASW3", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e2/1", node_b="HQ-ASW4", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e2/2", node_b="HQ-ASW4", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e2/3", node_b="HQ-ASW5", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e3/0", node_b="HQ-ASW5", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e3/1", node_b="HQ-ASW6", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW4", interface_a="e3/2", node_b="HQ-ASW6", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e1/3", node_b="HQ-ASW7", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e2/0", node_b="HQ-ASW7", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e2/1", node_b="HQ-ASW8", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e2/2", node_b="HQ-ASW8", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e2/3", node_b="HQ-ASW9", interface_b="e0/3"),
    NodeToNodeConnection(node_a="HQ-DSW5", interface_a="e3/0", node_b="HQ-ASW9", interface_b="e1/0"),
    NodeToNodeConnection(node_a="HQ-DSW6", interface_a="e1/3", node_b="HQ-ASW7", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW6", interface_a="e2/0", node_b="HQ-ASW7", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW6", interface_a="e2/1", node_b="HQ-ASW8", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW6", interface_a="e2/2", node_b="HQ-ASW8", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-DSW6", interface_a="e2/3", node_b="HQ-ASW9", interface_b="e0/1"),
    NodeToNodeConnection(node_a="HQ-DSW6", interface_a="e3/0", node_b="HQ-ASW9", interface_b="e0/2"),
    NodeToNodeConnection(node_a="HQ-ASW1", interface_a="e1/1", node_b="PC1", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW1", interface_a="e1/2", node_b="PC2", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW2", interface_a="e1/1", node_b="PC3", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW2", interface_a="e1/2", node_b="PC4", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW3", interface_a="e1/1", node_b="PC5", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW3", interface_a="e1/2", node_b="PC6", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW4", interface_a="e1/1", node_b="PC7", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW4", interface_a="e1/2", node_b="PC8", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW5", interface_a="e1/1", node_b="PC9", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW5", interface_a="e1/2", node_b="PC10", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW6", interface_a="e1/1", node_b="PC11", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW6", interface_a="e1/2", node_b="PC12", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW7", interface_a="e1/1", node_b="PC13", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW7", interface_a="e1/2", node_b="PC14", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW8", interface_a="e1/1", node_b="PC15", interface_b="eth0"),
    NodeToNodeConnection(node_a="HQ-ASW9", interface_a="e1/1", node_b="PC16", interface_b="eth0"),
]

dc_device_inventory = [
    IOL_Node(name="DataCenter-Router", image=Image.IOL_ROUTER, icon=Icon.ROUTER, device_role=DeviceRole.ROUTER, left=2075, top=1275, ethernet=2, mgmt_ip="192.168.110.22" ),
    IOL_Node(name="DC-ASW1", image=Image.IOL_SWITCH, icon=Icon.SWITCH_L2, device_role=DeviceRole.SWITCH, left=2100, top=1600, mgmt_ip="192.168.110.23", ethernet=2),
    RHEL_Linux_Node(name="Backup-DHCP-Server", ram=2048, image=Image.LINUX_RHEL_10, left=1950, top=1950),
    RHEL_Linux_Node(name="DNS-Server", ram=2048, image=Image.LINUX_RHEL_10, left=2115, top=1950),
]

dc_device_connection_inventory = [
    NodeToNodeConnection(node_a="DataCenter-Router", interface_a="e0/2", node_b="DC-ASW1", interface_b="e0/1"),
    NodeToNodeConnection(node_a="DC-ASW1", interface_a="e0/2", node_b="Backup-DHCP-Server", interface_b="e0"),
    NodeToNodeConnection(node_a="DC-ASW1", interface_a="e0/3", node_b="DNS-Server", interface_b="e0"),
]

dc_management_connection_inventory = [
    NodeToNetworkConnection(node="DataCenter-Router", interface_label="e0/0", network="Management2"),
    NodeToNetworkConnection(node="DC-ASW1", interface_label="e0/0", network="Management2"),
]




